iharent/urls.py
from django.contrib import admin
from django.urls import path,include
from ihas import views
from django.conf import settings
from django.conf.urls.static import static


# Uygulamada gidecek URL'leri burada tanımla
# Proje içinde uygulama kurulduğunda nested url tanımı için "include" fonksiyonu kullan
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('ihas/', include("ihas.urls")),
    path('user/', include("user.urls")),
]

# Media klasörünün yolunu aşağıdaki gibi ver
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ihas/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

# Uygulama içinde uygulama oluşturursan app_name yazmak zorundasın.
app_name = "ihas"

# Oluşturduğun yeni uygulama URL' lerini aşağıdaki gibi verebilirsin.
# Name değişkenine göre gideceğin yeri referanslayabilirsin.
urlpatterns = [
    path('dashboard/', views.dashboard, name="dashboard"),
    path('addiha/', views.addiha, name="addiha"),
    path('update/<int:id>', views.updateiha, name="update"),
    path('delete/<int:id>', views.deleteiha, name="delete"),
    path('', views.ihas, name="ihas"),

]

user/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

# Uygulama oluşturduktan sonra URL için app_name kullanmak zorundasın.

app_name = "user"

# User uygulaması URL'leri
urlpatterns = [
    path('register/', views.register, name="register"),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),

]

templates/includes/navbar.html
<!DOCTYPE html>
{% load static %} <!--template için gerekli css, js dosyalarına bu fonksiyonla ulaşabilirsin-->
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/navbar.css' %}"> <!--css yolunu bu şekilde vermelisin-->
    <title>Navbar</title>
</head>
<body>

    <!--Navbar-->
    <nav class="navbar bg-light">
        <div class="logo">
            <a href="{% url 'index' %}">
                <img src="https://cdnik.baykartech.com/media/images/contents/hr-logo.png" alt="">
            </a>
        </div>
        <div class="content">
            <a href="{% url 'ihas:ihas' %}" class="iha">
                İHALAR
            </a>
        </div>
        <div class="logs">
            <!--Navbar log işlem kontrolleri-->
            {% if request.user.is_authenticated %}
                <a href="{% url 'ihas:dashboard' %}" class="">
                    Dashboard
                </a>
                <a href="{% url 'user:logout' %}" class="">
                    Çıkış Yap
                </a>
            {% else %}
                <a href="{% url 'user:login' %}" class="">
                    Giriş Yap
                </a>

            {% endif %}
            <a href="{% url 'user:register' %}" class="">
                Kayıt Ol
            </a>
        </div>
      </nav>
</body>
</html>